### ISSUE TITLE
Receives 400 Bad Request when message is too long

### ISSUE THREAD

**Issue by yammmt** [yammmt/weekly-atcoder-report#2]
From my environment, this script raises 400 error. I don't know why because I didn't search this error at all.

```console
❯ bundle exec ruby main.rb
/Users/yammmt/git/weekly-atcoder-report/vendor/bundle/ruby/3.0.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response': 400 Bad Request (RestClient::BadRequest)
        from /Users/yammmt/git/weekly-atcoder-report/vendor/bundle/ruby/3.0.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
        from /Users/yammmt/git/weekly-atcoder-report/vendor/bundle/ruby/3.0.0/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
        from /Users/yammmt/git/weekly-atcoder-report/vendor/bundle/ruby/3.0.0/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
        from /Users/yammmt/.rbenv/versions/3.0.1/lib/ruby/3.0.0/net/http.rb:960:in `start'
        from /Users/yammmt/git/weekly-atcoder-report/vendor/bundle/ruby/3.0.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
        from /Users/yammmt/git/weekly-atcoder-report/vendor/bundle/ruby/3.0.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
        from /Users/yammmt/git/weekly-atcoder-report/vendor/bundle/ruby/3.0.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
        from /Users/yammmt/git/weekly-atcoder-report/vendor/bundle/ruby/3.0.0/gems/rest-client-2.1.0/lib/restclient.rb:70:in `post'
        from /Users/yammmt/git/weekly-atcoder-report/slack/slack.rb:87:in `send_report'
        from main.rb:18:in `<main>'
```

https://github.com/yammmt/weekly-atcoder-report/blob/3e8384a0d170fc905702ac7e893f80377ed41cc5/slack/slack.rb#L87

~~Is this an issue from WebHook URL?~~ Maybe an issue from message length.

**Comment by yammmt** [comment]
The following article indicates that my message was too long (> 40,000 characters):
https://api.slack.com/changelog/2018-04-truncating-really-long-messages

However, I add a debug code to the following line and then hit `pp msg` and save it as a file, its file size seems to be small enough (6,163 < 40,000). 🤔 

```console
diff --git a/slack/slack.rb b/slack/slack.rb
index 285bab1..8c8d692 100644
--- a/slack/slack.rb
+++ b/slack/slack.rb
@@ -83,6 +83,7 @@ module Slack
                           }
                         })
     end
+    binding.irb
 
     RestClient.post(WEBHOOK_URL, msg.to_json)
   end
```

```console
irb(Slack):007:0> File.open('test.txt', 'w') { |f| f.write(msg) }
=> 6163
irb(Slack):008:0> msg.to_json.size
=> 5976
```

**Comment by yammmt** [comment]
If I send a brief message, this system works well. Maybe it's a message length issue however I couldn't find any crucial information.

```console
irb(Slack):028:0> RestClient.post(WEBHOOK_URL, msg.to_json)
=> <RestClient::Response 200 "ok">
irb(Slack):029:0> pp msg.to_json
"{\"blocks\":[{\"type\":\"header\",\"text\":{\"type\":\"plain_text\",\"text\":\":newspaper: weekly atcoder report :newspaper:\"}}]}"
=> "{\"blocks\":[{\"type\":\"header\",\"text\":{\"type\":\"plain_text\",\"text\":\":newspaper: weekly atcoder report :newspaper:\"}}]}"
```
